'use client';

import { formatISO } from 'date-fns';
import { type NextPage } from 'next';
import Head from 'next/head';
import type { Day } from '@prisma/client';
import { Calendar } from '~/components';
import { prisma } from '~/server/db';

interface HomeProps {
  days: Day[];
  closedDays: string[];
}

const Home: NextPage<HomeProps> = ({ days, closedDays }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Calendar days={days} closedDays={closedDays} />
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const days = await prisma.day.findMany();
  const closedDays = (await prisma.closedDay.findMany()).map((day) =>
    formatISO(day.date)
  );

  return { props: { days, closedDays } };
}

export default Home;
