'use client';

import { type NextPage } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import { Calendar, Menu, Spinner } from '~/components';
import { DateObject } from '~/utils/types';
import { api } from '~/utils/api';

const Home: NextPage = () => {
  const [date, setDate] = useState<DateObject>({
    justDate: null,
    dateTime: null,
  });

  useEffect(() => {
    if (date.dateTime) checkMenuStatus();
  }, [date.dateTime]);

  const { mutate: checkMenuStatus, isSuccess } =
    api.menu.checkMenuStatus.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {!date.dateTime && <Calendar setDate={setDate} date={date} />}
        {date.dateTime && isSuccess ? (
          <Menu />
        ) : (
          <div className='flex h-screen items-center justify-center'>
            <Spinner />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
